@startuml classDiagram
class Datasource {
    -filePaths : String[]
    +getData(timestamp) : timeseriesData
}

class GUI {
    -controller : Controller
    +start() : void
    +stop() : void
    +update() : void
    +getController() : Controller
}
class Controller {
    -activeSensors : SensorConfig[]
    -connector : Connector
    -formatter : Formatter
    +requestData(Datasource,timestamp) : timeseriesData
    +requestConfig(SensorManager) : SensorConfig
    +requestFormat(Formatter,SensorConfig,timeseriesData) : formattedData
    +requestConnection(Connector) : boolean
    +requestPublish(Connector,formattedData) : boolean
}
class Connector {
    +connectTo(SensorConfig) : boolean
    +publishTo(SensorConfig,formattedData) : boolean
}
class Formatter {
 +format(timeseriesData) : formattedData
}
abstract class SensorManager {
 +configureSensor() : SensorConfig
}
class SensorManager {
 +configureSensor() : SensorConfig
}
class SensorConfig {
    -id : int
    -type : String
    -channel : String
    +getSensorConfig() : SensorConfig
}

class ScenarioConfig {
    -id : int
    -type : String
    -channel : String
    +getSensorConfig() : SensorConfig
}


SensorManager "1" -l-> "*" SensorConfig : configures
SensorManager "1" -l-> "1" ScenarioConfig : configures

GUI "1" -d-> "*" Controller : inputs commands
Controller "1" -d-> "*" GUI : status updates

Controller "1" o-d- "1" ScenarioConfig : controls

Controller "1" o-d- "*" SensorConfig : controls
Controller "1" -d-> "*" SensorManager : requests-config
Controller <.l. Datasource
SensorConfig "1 "*-- "1" Formatter : formats data
Controller "1" *-r- "1" Connector

@enduml
