@startuml
GUI -> Controller: Request Scenario

SensorConfig <- Controller: Request Scenario Config
SensorConfig --> Controller: Scenario & Sensor Configuration

Datasource <- Controller: "Fill" sensors with data
Datasource --> Controller: Sensors with data



SensorConfig -> Reformatter: Formatting Request
SensorConfig <-- Reformatter: Reformatted Messages
GUI <-- Controller: Ready to publish
GUI -> Controller: Publish

Controller -> Connector: Publish (SensorConfigs)
Connector -> SensorBoard: Send Messages Request
Controller <-- Connector: Publish complete
GUI <-- Controller: Publish complete
@enduml
